excluded:
- WeatherForecast/Application/AppDelegate.swift
- WeatherForecast/Application/SceneDelegate.swift
- WeatherForecastUITests
- WeatherForecastTests

disabled_rules:
- trailing_whitespace
- line_length
- force_cast

identifier_name:
  excluded:
    - dt
    - id
