excluded:
- WeatherForecast/Application/AppDelegate.swift
- WeatherForecast/Application/SceneDelegate.swift
- WeatherForecastUITests
- WeatherForecastTests

identifier_name:
  excluded:
    - dt
    - id
