disabled_rules:
- trailing_whitespace

excluded:
- WeatherForecast/Core/Sources/Application/AppDelegate.swift
- WeatherForecast/Core/Sources/Application/SceneDelegate.swift
- WeatherForecastUITests
- WeatherForecastTests

identifier_name:
  excluded:
    - id
