excluded:
- WeatherForecast/Core/Sources/Application/AppDelegate.swift
- WeatherForecast/Core/Sources/Application/SceneDelegate.swift
- WeatherForecastUITests
- WeatherForecastTests

disabled_rules:
- trailing_whitespace

identifier_name:
  excluded:
    - dt
    - id
